name: GitHub Actions Demon

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows'
  workflow_dispatch:
  schedule:
      - cron: '15 6 * * 0'
  pull_request:
    branches: 
      - main

jobs:
  jonb1:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "event: ${{github.event_name}}"
          echo "branch is ${{ github.ref }}"
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains:"
          tree
